---
- name: Install Vector | DNF ensure datadog repo GPG key imported
  ansible.builtin.rpm_key:
    state: present
    key: https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public
  become: true

- name: Install Vector | DNF 
  ansible.builtin.dnf:
    name: "https://yum.vector.dev/stable/vector-0/{{ ansible_architecture }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm"
    state: present
  notify: restart vector
  become: true