---
- name: Vector | Ensure group "vector" exists
  become: true
  ansible.builtin.group:
    name: "{{ role_vector_group }}"
    state: present

- name: Vector | Add the user 'vector' with a bash shell, appending the group 'vector' and groups for scraping
  become: true
  ansible.builtin.user:
    name: "{{ role_vector_user }}"
    group: "{{ role_vector_group }}"
    groups: "{{ role_vector_groups | default('') }}"
    shell: /usr/sbin/nologin
    create_home: true
    append: true
  
- name: Vector| Install package
  ansible.builtin.include_tasks:
    file: install_{{ ansible_facts.pkg_mgr }}.yml

- name: Configure Vector | Ensure what directory exists
  file:
    path: "{{ vector_config_dir }}"
    state: directory
    mode: 0644

- name: Configure Vector | Template config
  ansible.builtin.template:
    src: vector.yml.j2
    mode: 0644
    dest: "{{ vector_config_dir }}/vector.yml"

- name: Configure Service | Template systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: 0644