---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  
  - name: Include vars
    ansible.builtin.include_vars:
      dir: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/vars/'
      extensions:
        - 'yml'
  
  - name: Execute vector
    command: vector --version
    changed_when: false
    register: vector_version_rc

  - name: Check valid config
    become: true
    command: vector validate --no-environment {{ vector_config_dir }}/vector.yml
    register: vector_config_valid

  - name: Assert vector is installed
    assert:
      that:
        - vector_version_rc is success
        - vector_config_valid is success