---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu
    image: ubuntu:latest
    dockerfile: ../resources/Dockerfile.j2
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
